# NOTA PARA USUARIOS WINDOWS: usad ";" en vez de ":" como separador de
# "paths" y usad "\" en vez de "/" como separador de directorios.

# Para compilar todo:
compile:
	# Crear el direction bin si no está creado
	mkdir -p bin
	# Compilar todo el código fuente
	javac -d bin -cp src src/*.java
